#!/usr/bin/env bash
# 🅳🅾🆃🅵🅸🅻🅴🆂 (v0.2.468) - <https://dotfiles.io>
# Made with ♥ in London, UK by @sebastienrousseau
# Copyright (c) 2015-2024. All rights reserved
# License: MIT

## 🆅🅰🆁🅸🅰🅱🅻🅴🆂 - Set Dotfiles variable.
HOSTNAME=$(hostname -f)                 # hostname of the machine.
INPUTRC=${HOME}/.inputrc                # set INPUTRC (so that .inputrc is respected)
OS_ARCH=$(uname -m)                     # machine hardware name.
OS_NAME=$(uname)                        # operating system name.
OS_VERSION=$(uname -r)                  # operating system version number.
SSL_CERT_FILE=${HOME}/cacert.pem        # set the SSL_CERT_FILE environment variable.
# USER_LANGUAGE="en_GB.UTF-8"             # default language.
# USER=$(whoami)                        # current user name.

## 🅴🆇🅿🅾🆁🆃🆂 - Export the variables.
export ARCHFLAGS="-arch ${OS_ARCH}"     # archflags for the current machine.
export DOTFILES_VERSION='0.2.468'       # version of the dotfiles.
export DOTFILES="${HOME}"/.dotfiles/lib # path to the cross plaform dotfiles.
export HOSTNAME=${HOSTNAME}             # hostname of the machine.
export INPUTRC=${INPUTRC}               # set INPUTRC (so that .inputrc is respected)
export LANG=${USER_LANGUAGE}            # default language.
export LANGUAGE=${USER_LANGUAGE}        # default language.
export LC_ALL=${USER_LANGUAGE}          # default language.
export LC_CTYPE=${USER_LANGUAGE}        # default language.
export OS_ARCH                          # machine hardware name.
export OS_NAME                          # operating system name.
export OS_VERSION                       # operating system version number.
export SSL_CERT_FILE=${SSL_CERT_FILE}   # set the SSL_CERT_FILE environment variable.
export TERM=xterm-256color              # default terminal color.
# export USER                             # current user name.

## 🅻🅾🅰🅳🅴🆁🆂 - Load the dotfiles.
for loaders in "${DOTFILES}"/*.sh; do
  # shellcheck source=/dev/null
  . "${loaders}"
done

# Remove duplicates in zsh $PATH
# shellcheck disable=SC2034
typeset -aU path

# Initialize the completion system
autoload -Uz compinit

# Enable colors in prompt
autoload -Uz colors && colors

# Starting to find autocorrect rather annoying...
unsetopt correct_all

eval "$(starship init zsh)"

# antidote load

neofetch 


eval $(thefuck --alias)

setopt autocd              # change directory just by typing its name
#setopt correct            # auto correct mistakes
setopt interactivecomments # allow comments in interactive mode
setopt magicequalsubst     # enable filename expansion for arguments of the form ‘anything=expression’
setopt nonomatch           # hide error message if there is no match for the pattern
setopt notify              # report the status of background jobs immediately
setopt numericglobsort     # sort filenames numerically when it makes sense
setopt promptsubst         # enable command substitution in prompt
